version: '3'

services:
  selfhostedbackgroundservice:
    image: selfhostedbackgroundservice
    build:
      context: ./SelfHostedBackgroundService
      dockerfile: Dockerfile
    ports:
    - 5100:5100
  backgroundhostedservices:
    image: backgroundhostedservices
    build:
      context: ./BackgroundHostedServices
      dockerfile: Dockerfile
    ports:
    - 5101:5123