version: '3'

services:
  selfhostedbackgroundservice:
    image: selfhostedbackgroundservice
    build:
      context: ./SelfHostedBackgroundService
      dockerfile: Dockerfile
    depends_on:
    - backgroundhostedservices
  backgroundhostedservices:
    image: backgroundhostedservices
    build:
      context: ./BackgroundHostedServices
      dockerfile: Dockerfile
    depends_on:
    - messagesquare
    ports:
    - 5101:5123
  messagesquare:
    image: rabbitmq
    ports:
    - 5670:5672